#!/bin/bash

# toshitai starts at 23:30, and ends at 23:59, so duration is 1740 secs
now_date=`date +%Y%m%d`
start_hours=23
start_mins=30
start_time=`date --date "$now_date $start_hours hours $start_mins minutes" +%s`
now_time=`date +%s`
duration=1743

echo "Now   : " `date +"%Y/%m/%d %H:%M:%S"`
echo "Starts: " `date --date "$now_date $start_hours hours $start_mins minutes" +"%Y/%m/%d %H:%M:%S"`

# wait until 20 secs after start
((waiting = start_time - now_time + 20)) 
if [ $waiting -gt 0 ] ; then
  printf 'Wait recording for '$waiting' secs\n'
  sleep $waiting
fi

# The base episode is 189 on 2019/11/12
base_date=20191112
base_episode=189
base_date_s=`date --date "$base_date" +%s`
now_date_s=`date --date "$date" +%s`
((diff = (now_date_s - base_date_s) / 60 / 60 / 24 / 7))
((episode = base_episode + diff))

path=""
file="$episode"_"$now_date"
full="$path""$file"

while [ -e "$full".mp4 ]
do
  echo "Already exists "$file" file! We connect some random characters."
  file+="_"
  file+=`date +%N`
done

printf 'Recording for '$duration' secs to '$file'.mp4\n\n'

ffmpeg -protocol_whitelist file,http,https,tcp,tls,crypto -i https://www.uniqueradio.jp/agplayer5/hls/mbr-ff.m3u8 -movflags faststart -t $duration -c copy $full.mp4

printf '\nSaved to '$file'.mp4\n'
